#fit 1
text2workspace.py ../../../output/cards/cmbcards_woTauSpinner_embedding/ztt_mm_0jet_1.txt 
#fit 2
text2workspace.py ../../../output/cards/cmbcards_woTauSpinner_embedding/ztt_mm_1jet_zpt_loose_2.txt 
#fit 3
text2workspace.py ../../../output/cards/cmbcards_woTauSpinner_embedding/ztt_mm_1jet_zpt_medium_3.txt 
#fit 4
text2workspace.py ../../../output/cards/cmbcards_woTauSpinner_embedding/ztt_mm_1jet_zpt_tight_4.txt 
#fit 5
text2workspace.py ../../../output/cards/cmbcards_woTauSpinner_embedding/ztt_mm_2jet_cp_5.txt 
#fit 6
text2workspace.py ../../../output/cards/cmbcards_woTauSpinner_embedding/ztt_mm_vbf_6.txt 
#fit 7
text2workspace.py ../../../output/cards/cmbcards_woTauSpinner_embedding/ztt_mm_1bjet_7.txt 
#fit 8
text2workspace.py ../../../output/cards/cmbcards_woTauSpinner_embedding/ztt_mm_2bjet_8.txt 
#fit 9
text2workspace.py ../../../output/cards/cmbcards_woTauSpinner_embedding/ztt_mm_MSSM_btag_9.txt 
#fit 10
text2workspace.py ../../../output/cards/cmbcards_woTauSpinner_embedding/ztt_mm_0jet_10.txt 
#fit 11
text2workspace.py ../../../output/cards/cmbcards_woTauSpinner_embedding/ztt_mm_1jet_zpt_loose_11.txt 
#fit 12
text2workspace.py ../../../output/cards/cmbcards_woTauSpinner_embedding/ztt_mm_1jet_zpt_medium_12.txt 
#fit 13
text2workspace.py ../../../output/cards/cmbcards_woTauSpinner_embedding/ztt_mm_1jet_zpt_tight_13.txt 
#fit 14
text2workspace.py ../../../output/cards/cmbcards_woTauSpinner_embedding/ztt_mm_2jet_cp_14.txt 
#fit 15
text2workspace.py ../../../output/cards/cmbcards_woTauSpinner_embedding/ztt_mm_vbf_15.txt 
#fit 16
text2workspace.py ../../../output/cards/cmbcards_woTauSpinner_embedding/ztt_mm_1bjet_16.txt 
#fit 17
text2workspace.py ../../../output/cards/cmbcards_woTauSpinner_embedding/ztt_mm_2bjet_17.txt 
#fit 18
text2workspace.py ../../../output/cards/cmbcards_woTauSpinner_embedding/ztt_mm_MSSM_btag_18.txt 


